CREATE TABLE [tbl_1_Schema] (
  [wedstrijd] DOUBLE ,
  [Thuis1] DOUBLE ,
  [Uit1] DOUBLE ,
  [Thuis2] DOUBLE ,
  [Uit2] DOUBLE ,
  [Thuis3] DOUBLE ,
  [Uit3] DOUBLE ,
  [Thuis4] DOUBLE ,
  [Uit4] DOUBLE ,
  [Thuis5] DOUBLE ,
  [Uit5] DOUBLE ,
  [Thuis6] DOUBLE ,
  [Uit6] DOUBLE ,
  [Thuis7] DOUBLE ,
  [Uit7] DOUBLE ,
  [Thuis8] DOUBLE ,
  [Uit8] DOUBLE ,
  [F18] VARCHAR (255)
)
